configfile: "config/config.yaml"

REFERENCE_GRAPH_VCF = config["graph_vcf"]
REFERENCE_CALLSET_VCF = config["callset_vcf"]
REFERENCE_FASTA = config["reference_fasta"]
INPUT_DIR = config["input"]
OUTPUT_DIR = config["output"]
THREADS_NUMBER = config["threads"]
LIBRARY_TYPE = config["library_type"]

if LIBRARY_TYPE == "pe":
    samples, = glob_wildcards(
       f"{INPUT_DIR}/{{sample}}_1.fastq.gz")
elif LIBRARY_TYPE == "se":
    samples, = glob_wildcards(
       f"{INPUT_DIR}/{{sample}}.fastq.gz")

print(samples)


rule all:
    input:
        expand("{output}/results/{sample}_bi_genotyping.vcf.gz", output=OUTPUT_DIR, sample=samples),
        expand("{output}/results/merged-genotypes_bi.vcf.gz", output=OUTPUT_DIR)

rule unzip_reference:
    """
    Unzip reference genome in fasta format and input graph.vcf
    """
    input:
        zipped_vcf = REFERENCE_GRAPH_VCF,
        zipped_fasta = REFERENCE_FASTA
    output:
        unzipped_vcf = temp("{output}/ref/graph.vcf"),
        unzipped_fasta = temp("{output}/ref/reference.fasta")
    shell:
        """
        gunzip -c {input.zipped_fasta} > {output.unzipped_fasta}
        gunzip -c {input.zipped_vcf} > {output.unzipped_vcf}
        """


rule pangenie_index:
    """
    Create index for PanGenie
    """
    input:
       vcf = rules.unzip_reference.output.unzipped_vcf,
       fasta = rules.unzip_reference.output.unzipped_fasta
    output:
       directory("{output}/index")
    log:
       "{output}/index/indexing.log"
    threads: 
        THREADS_NUMBER
    params:
       out_prefix = "{output}/index/reference_index"
    shell:
       """
       PanGenie-index -v {input.vcf} -r {input.fasta} -o {params.out_prefix} -t {threads} &> {log}
       """


if LIBRARY_TYPE == "pe":

  rule merge_reads:
     """
     Merge forward and reverse reads
     """
     input:
        forward_reads = f"{INPUT_DIR}/{{sample}}_1.fastq.gz",
        reverse_reads = f"{INPUT_DIR}/{{sample}}_2.fastq.gz"
     output:
        merged_reads = temp("{output}/samples/{sample}_merged.fasta")
     shell:
        """
        zcat {input.forward_reads} {input.reverse_reads} > {output.merged_reads}
        """


  rule pangenie_genotype:
     """
     Run genotyping
     """
     input:
        reads = rules.merge_reads.output.merged_reads,
        index_file = rules.pangenie_index.output
     output:
        vcf = temp("{output}/results/{sample}_multi_genotyping.vcf")
     log:
        "{output}/results/{sample}_genotyping.log"
     params:
        out_prefix = "{output}/results/{sample}_multi",
        index = "{output}/index/reference_index"
     threads:
        THREADS_NUMBER
     shell:
        """
        PanGenie -f {params.index} -i {input.reads} -o {params.out_prefix} -t {threads} -j {threads} -s {wildcards.sample} &> {log}
        """

else:

    rule unzip_reads:
        """
        Unzip file with reads
        """
        input:
            zipped_reads = f"{INPUT_DIR}/{{sample}}.fasta.gz"
        output:
            unzipped_reads = temp("{output}/samples/{sample}.fasta")
        shell:
            """
            gunzip -c {input.zipped_reads} > {output.unzipped_reads}
            """


    rule pangenie_genotype:
         """
         Run genotyping
         """
         input:
            reads =  rules.unzip_reads.output.unzipped_reads,
            index_file = rules.pangenie_index.output
         output:
            vcf = temp("{output}/results/{sample}_multi_genotyping.vcf")
         log:
            "{output}/results/{sample}_genotyping.log"
         params:
            out_prefix = "{output}/results/{sample}_multi",
            index = "{output}/index/reference_index"
         threads:
            THREADS_NUMBER
         shell:
            """
            PanGenie -f {params.index} -i {input.reads} -o {params.out_prefix} -t {threads} -j {threads} -s {wildcards.sample} &> {log}
            """


rule convert_genotypes_to_biallelic:
  """
  Convert genotyped VCF to biallelic representation
  """
  input:
     vcf = rules.pangenie_genotype.output.vcf,
     biallelic = REFERENCE_CALLSET_VCF
  output:
     bi = "{output}/results/{sample}_bi_genotyping.vcf.gz",
     bi_tbi = "{output}/results/{sample}_bi_genotyping.vcf.gz.tbi"
  shell:
     """
     cat {input.vcf} | python3 scripts/convert-to-biallelic.py {input.biallelic} | bgzip > {output.bi}
     tabix -p vcf {output.bi}
     """


rule merge_vcfs:
  """
  Merges the single-sample VCFs into one multi-sample VCF
  """
  input:
     bi = expand("{{output}}/results/{sample}_bi_genotyping.vcf.gz", sample = samples)
  output:
     merged_bi = "{output}/results/merged-genotypes_bi.vcf.gz"
  shell:
     """
     bcftools merge {input.bi} -Oz -o {output.merged_bi}
     tabix -p vcf {output.merged_bi}
     """
